services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3306:3306'
    networks: 
      - nlw-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  nlw-network:
    driver: bridge
